[workspace]
authors = ["Joe Helbing <joehelbing@gmail.com>"]
channels = ["conda-forge"]
name = "Fourier-series-tattoo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
manim = ">=0.19.0,<0.20"
pandas = ">=2.3.2,<3"
matplotlib = ">=3.10.6,<4"
librosa = ">=0.11.0,<0.12"
scipy = ">=1.16.1,<2"
yt-dlp = ">=2025.9.5,<2026"
ffmpeg = ">=7.1.1,<8"
